version: '3.8'

services:
  service_discovery:
    image: nadea39/service-discovery:v1.0.0
    container_name: service_discovery_container
    command: ["python", "serviceDiscovery.py"]
    ports:
      - "8500:8500"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  
  notifications:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications_container
    command: ["python", "notificationService.py"]
    depends_on:
      service_discovery:
        condition: service_healthy
    ports:
      - "8600:8600"
    environment:
      - PYTHONUNBUFFERED=1
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - SERVICE_DISCOVERY_URL=http://service_discovery:8500
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge