version: '3.8'

services:
  service_discovery:
    image: nadea39/service-discovery:v1.0.0
    container_name: service_discovery_container
    ports:
      - "8500:8500"
    networks:
      - game_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  microservices-network:
    driver: bridge